### ISSUE TITLE
Build on OSX

### ISSUE THREAD

**Issue by bagobor** [cyberegoorg/cetech#142]
- please update build documentation to change python -> python3 and pip -> pip3 for OSX platform.
- 'python3 externals.py' is failed with log:
```
...
Clone: libyaml
Build: libyaml
Traceback (most recent call last):
  File "externals.py", line 318, in <module>
    main()
  File "externals.py", line 307, in main
    verbose=args_parse.verbose)
  File "externals.py", line 282, in make_externals
    verbose=verbose)
  File "externals.py", line 240, in do_job
    verbose=verbose)
  File "externals.py", line 146, in build
    commands = body['build'][platform_]
KeyError: 'darwin64'
```

Do you have any ideas how to fix it?

**Comment by bagobor** [comment]
I checked 'external/darwin64/dynlib/' folder - it's empty. 
It look like something wrong with build configuration.

**Comment by OndraVoves** [comment]
Hi thx for reporting =). Please try now. (fix commit: https://github.com/cyberegoorg/cetech/commit/959ab2af5ed3352ce2c115d5106636d37cd9e63c).
