### ISSUE TITLE
OSX build

### ISSUE THREAD

**Issue by bagobor** [cyberegoorg/cetech#165]
1. mistyping in documentation: Generate project $ pthon build.py -g
2. 

```
~/d/g/cetech> python3 build.py -g
Runing Protobuild.exe.
Traceback (most recent call last):
  File "build.py", line 204, in <module>
    main()
  File "build.py", line 193, in main
    debug=args.debug)
  File "build.py", line 166, in make
    run_protobuild(config=config, platform_=platform_)
  File "build.py", line 155, in run_protobuild
    cmds.append(PLATFORMS_PROTOBUILD[platform_])
KeyError: 'darwin64'
```

**Comment by OndraVoves** [comment]
Hi =) Now is supported only Linux and Windows because i do not have mac computer. But if i have time i can write "blind" port.

**Comment by bagobor** [comment]
Can you provide some info so I can try to fix by myself?

**Comment by OndraVoves** [comment]
Make blind port in this commit => 9f3da0ea03fe690605608f6c0aad366fe64c1af9
Before build you must build externals "python3 externals/externals.py -v"

**Comment by bagobor** [comment]
Error:
```
FileNotFoundError: [Errno 2] No such file or directory: '.libs/libnanomsg.so.4.0.0'
```
while building externals.

**Comment by OndraVoves** [comment]
1. Find lib in externals/src/nanomsg/.libs 
2. on line 249 in [externals/externals.yml](https://github.com/cyberegoorg/cetech/blob/master/externals/externals.yml#L249) change .libs/libnanomsg.so.4.0.0 and libnanomsg.so to right lib name 
3. on line 25 in [Build/Projects/NNanomsg](https://github.com/cyberegoorg/cetech/blob/master/Build/Projects/NNanomsg.definition#L25) change libnanomsg.so change to right lib name

**Comment by bagobor** [comment]
I see .. 
I'll check all build script for same problems tonight.
so -> dynlib and libraries naming are different for different platforms.

**Comment by OndraVoves** [comment]
Please can you fix it and send pull request?

**Comment by bagobor** [comment]
sure :)
