### ISSUE TITLE
Rewrite to good old C

### ISSUE THREAD

**Issue by OndraVoves** [cyberegoorg/cetech#200]
Yes, next rewrite... From my point of view (+some experiments) C is winner for Data-Driven engine because C is very simple sexy explicit language with full control on everything. And if you need some feature you CAN write it yourself. Thanks Ken Thompson and Dennis Ritchie =)

**Comment by nem0** [comment]
Why not "C with classes"?

**Comment by OndraVoves** [comment]
What do you mean "C with classes"? Something as "Orthodox C++" ?

**Comment by nem0** [comment]
Yes, something like that. Basically C with a few C++ syntactic sugars. C is great but some features can be less safe or more verbose with no added benefit.

**Comment by OndraVoves** [comment]
"C with classes" is good approach. But actually i have idea for "heavy" modular micro-engine where engine is like a OS kernel. This idea is based on http://bitsquid.blogspot.cz/2014/04/building-engine-plugin-system.html. Engine is small core that is write in pure C. Module/Core "export" api as a C struct-of-functions. with this approach is very simple write "wrap" for that core function to other language C++, lua, python, etc... I belive that approach is good for fast iteration, modification and experiment with new features. Because i can write module in many language eg. prototype in Lua and later rewrite it to C or C++ for speed and i don't need edit or compile another module. Maybe is bad and i fail =D
